### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by nakayama-bird** [nakayama-bird/metime-meals#35]
### 概要
- MVPリリースまでの実装予定の内容です
- 現状ストーリーポイント68×2=136時間
- GitHubProjectをpublic設定済みです
### 実装内容予定の機能
- [ ] ユーザー登録機能
- [ ] ログイン・ログアウト機能
- [ ] 投稿一覧機能（カード）
- [ ] 投稿一覧機能（Gppgle Maps APIを使用した地図）
- [ ] 新規投稿機能
- [ ] Gppgle Maps APIを使用したオートコンプリート機能
- [ ] AnazonS3を使用した画像投稿機能
- [ ] 投稿詳細機能
- [ ] 投稿編集機能
- [ ] 投稿削除機能
- [ ] いいね機能
- [ ] 自分のいいねした投稿を表示する機能
- [ ] 自分の投稿を表示する機能
- [ ] ransackを使った検索機能（カード）
- [ ] ransackを使った検索機能（Gppgle Maps APIを使用した地図）
- [ ] 詳細画面でのXシェア機能
### 必要なページ
- [ ] トップページ
- [ ] ヘッター
- [ ] ログイン前のヘッター
- [ ] フッター
- [ ] 投稿一覧画面（カード）
- [ ] 投稿一覧画面（地図）
- [ ] 新規投稿画面
- [ ] 投稿詳細画面
- [ ] 地図上でピンをクリックした際の投稿詳細画面の一部
- [ ] 投稿編集画面
- [ ] マイページでのいいね一覧画面
- [ ] マイページでの自分の投稿一覧

**Comment by tarakish** [comment]
Issue内のタスクまで良く書けていると思います！LGTMです！
MVPリリースに向けて開発頑張ってください。

**Comment by nakayama-bird** [comment]
確認していただきありがとうございます！
