### ISSUE TITLE
MVPリリース_レビュー依頼

### ISSUE THREAD

**Issue by nakayama-bird** [nakayama-bird/metime-meals#72]
## 各種情報
サービス名：Me Time Meals（ミータイムミールズ）
サービスURL：https://metime-meals-21937e9c3179.herokuapp.com/
Github：https://github.com/nakayama-bird/metime-meals

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [X] 会員登録・ログイン機能
    - [X] Sorceryを使用して、ログイン機能を実装
- [X] 投稿機能
    - [X] Google Maps APIを利用した場所の投稿機能
    - [X] 料理ジャンルの投稿
    - [X] 各種タグの投稿
    - [ ] 来店時間帯の投稿
    - [X] 飲食した際の金額の投稿
    - [X] AmazonS3を利用した画像投稿
- [X] 投稿一覧機能
    - [X] Google Maps JavaScript APIを利用した地図上でのピン表示
- [X] 検索機能→カード一覧のみ
    - [X]  投稿内容、タグから投稿を検索できるようにする
    - [ ]  来店時間、金額から投稿を検索できるようにする
- [ ] いいね機能
    - [ ] ユーザーが気になるお店にいいねできる機能
    - [ ] マイページで自身がいいねした投稿一覧を表示できるようにする
- [ ] Xシェア機能
    - 各投稿をシェアできる機能の実装

### 本リリース時導入予定
- 投稿機能が主軸のアプリのため本リリースに回しました。
  - いいね機能
  - Xシェア機能

### 本リリースに導入するか検討中
- 必要かどうかや他の方法も含めて今後検討予定です。
  - 来店時間帯の投稿
  - 来店時間、金額から検索 
  - 地図での検索機能

### ユーザー関係
|ログイン機能|新規登録機能|
| :-: | :-: |
|![Image](https://github.com/user-attachments/assets/01be14ea-29cf-456d-8c86-986516081134)|![Image](https://github.com/user-attachments/assets/3d2653c9-3b06-4314-a972-953744dd5746)|

### 投稿関係
|新規投稿機能|投稿編集機能|
| :-: | :-: |
|![Image](https://github.com/user-attachments/assets/31aaf115-9bf6-4d5d-a431-08772e395eb0)|![Image](https://github.com/user-attachments/assets/6998e044-9aeb-4577-be9b-b48bc9fb510f)|

|投稿削除機能|オートコンプリート|
| :-: | :-: | 
|![Image](https://github.com/user-attachments/assets/ad3596f6-3b9a-4a37-9a46-a0eab66a851c)|![Image](https://github.com/user-attachments/assets/5809045f-123b-4bcd-8104-f3fbbeacc29a)|
### 投稿一覧画面
|カード一覧|地図一覧|
| :-: | :-: |
|![Image](https://github.com/user-attachments/assets/07d3c987-9780-4c6b-a739-ad5d91f6687b)|![Image](https://github.com/user-attachments/assets/24abe6f9-af50-41d5-8ebc-d79e1f056ae5)|
### 投稿検索関連（カードのみ）
|ワード検索|ジャンル検索|
| :-: | :-: |
|![Image](https://github.com/user-attachments/assets/311510ea-7c1b-4b7e-9a05-88d63832798b)|![Image](https://github.com/user-attachments/assets/d9f7927d-6af6-43d3-9f6d-9819a65888ee)|

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by nakayama-bird** [comment]
@Tsuchiya2 
ご確認いただきありがとうございます！
こちらのissueはクローズします。
